repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-tables
    # - mdformat-gfm
    # - mdformat-black
